// temporary: look at a Rocketbox hand close up
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
const q = new URLSearchParams( location.search );
const W = 1280, H = 720;
const renderer = new THREE.WebGLRenderer( { canvas: document.getElementById( 'c' ), antialias: true } );
renderer.setSize( W, H, false );
renderer.toneMapping = THREE.ACESFilmicToneMapping;
const scene = new THREE.Scene();
scene.background = new THREE.Color( 0x6a6e72 );
scene.add( new THREE.HemisphereLight( 0xcfe6ff, 0x3a3326, 1.2 ) );
const sun = new THREE.DirectionalLight( 0xffffff, 2.2 ); sun.position.set( 2, 4, 1.5 ); scene.add( sun );
const cam = new THREE.PerspectiveCamera( 35, W / H, 0.005, 20 );
const tl = new THREE.TextureLoader();
const tex = ( f, s ) => new Promise( r => tl.load( '/models/characters/' + f, t => { t.flipY = false; t.colorSpace = s ? THREE.SRGBColorSpace : THREE.NoColorSpace; r( t ); } ) );
const id = q.get( 'id' ) || 'm_army1';
const [ g, c, n ] = await Promise.all( [ new GLTFLoader().loadAsync( '/models/characters/' + id + '.glb' ), tex( id + '_c.jpg', true ), tex( id + '_n.jpg', false ) ] );
const root = g.scene;
let skin = null; const bones = {};
root.traverse( o => { if ( o.isBone ) bones[ o.name ] = o; if ( o.isSkinnedMesh ) { const lod = o.name.startsWith( 'lod1' ) || o.parent?.name?.startsWith( 'lod1' ); if ( ! lod && o.material?.name !== 'cards' ) skin = o; else o.visible = false; } } );
skin.material = new THREE.MeshStandardMaterial( { map: c, normalMap: n, roughness: 0.6 } );
scene.add( root );
root.updateMatrixWorld( true );
window.info = { bones: Object.keys( bones ), meshes: [] };
root.traverse( o => { if ( o.isMesh ) window.info.meshes.push( [ o.name, o.geometry.attributes.position.count, o.material?.name ] ); } );
window.view = ( o ) => {
	const b = bones[ o.bone || 'Bip01_R_Hand' ];
	const p = new THREE.Vector3().setFromMatrixPosition( b.matrixWorld );
	const [ yw, pt, d ] = o.cam || [ 30, 20, 0.35 ];
	const a = yw * Math.PI / 180, bb = pt * Math.PI / 180;
	cam.position.set( p.x + Math.sin( a ) * Math.cos( bb ) * d, p.y + Math.sin( bb ) * d, p.z + Math.cos( a ) * Math.cos( bb ) * d );
	cam.lookAt( p );
	skin.material.wireframe = !! o.wire;
	renderer.render( scene, cam );
	return p.toArray();
};
window.__ready = true;
